/** Communications Centre application service and command boundary. */
const CommunicationService = (() => {
  const CAMPAIGN_STATUSES = Object.freeze(["DRAFT", "READY_FOR_REVIEW", "APPROVED", "SCHEDULED", "SENDING", "TESTED", "SENT", "PARTIALLY_FAILED", "FAILED", "CANCELLED", "ARCHIVED"]);
  const TEMPLATE_STATUSES = Object.freeze(["ACTIVE", "ARCHIVED"]);
  const COMMANDS = Object.freeze({
    CreateCommunicationCampaign: "Communications.Create", UpdateCommunicationCampaign: "Communications.EditOwn",
    SaveCommunicationTemplate: "Communications.Template.Manage", SaveAudience: "Communications.Audience.Build",
    ResolveCampaignAudience: "Communications.Audience.Build", PreviewCommunication: "Communications.View",
    SendTestCommunication: "Communications.SendTest", ArchiveCommunicationCampaign: "Communications.EditOwn"
  });
  const BUILT_IN_TEMPLATE = Object.freeze({ id: "SYS-GENERAL-UPDATE", entityType: "CommunicationTemplate", name: "General program update", category: "General", subject: "An update for {{Participant.FirstName}}", htmlBody: "<p>Hello {{Participant.FirstName}},</p><p>Add your Schools Spectacular update here.</p><p>Regards,<br>{{Sender.DisplayName}}</p>", plainTextBody: "Hello {{Participant.FirstName}},\n\nAdd your Schools Spectacular update here.\n\nRegards,\n{{Sender.DisplayName}}", supportedMergeFields: CommunicationMergeService.getFields(), status: "ACTIVE", version: 1, system: true });

  function getWorkspace() {
    const user = require_("Communications.View"), campaigns = CommunicationRepositoryService.list("campaigns"), templates = templates_(), audiences = CommunicationRepositoryService.list("audiences"), events = CommunicationRepositoryService.list("events"), recipients = CommunicationRepositoryService.list("recipients");
    return { campaigns, templates, audiences, events: events.slice(0, 100), recipients: recipients.slice(0, 100), senderIdentities: senderIdentities_(user), mergeFields: CommunicationMergeService.getFields(), providerStatus: CommunicationEmailProviderService.status(), filterOptions: CommunicationAudienceService.getFilterOptions(), supportedFilters: CommunicationAudienceService.getSupportedFilters(), recipientTypes: CommunicationAudienceService.recipientTypes(), capabilities: communicationCapabilities_(user), repository: CommunicationRepositoryService.architecture(), metrics: metrics_(campaigns, templates, audiences, events), generatedAt: new Date().toISOString() };
  }
  function execute(commandName, input) {
    const name = String(commandName || ""), value = input || {};
    try {
      if (!COMMANDS[name]) return failure_(name, "COMMAND_NOT_FOUND", "The Communications command is not registered.");
      if (name === "CreateCommunicationCampaign" || name === "UpdateCommunicationCampaign") return success_(name, saveCampaign_(value));
      if (name === "SaveCommunicationTemplate") return success_(name, saveTemplate_(value));
      if (name === "SaveAudience") return success_(name, saveAudience_(value));
      if (name === "ResolveCampaignAudience") return success_(name, resolveAudience_(value));
      if (name === "PreviewCommunication") return success_(name, preview_(value));
      if (name === "SendTestCommunication") return success_(name, sendTest_(value));
      if (name === "ArchiveCommunicationCampaign") return success_(name, archiveCampaign_(value));
      return failure_(name, "COMMAND_NOT_FOUND", "The Communications command is not registered.");
    } catch (error) { return failure_(name, /required/i.test(error.message) ? "PERMISSION_DENIED" : "COMMAND_FAILED", error && error.message ? error.message : String(error)); }
  }
  function saveCampaign_(input) {
    const existing = input.id ? CommunicationRepositoryService.get("campaigns", input.id) : null, user = require_(existing ? (can_("Communications.EditAll") ? "Communications.EditAll" : "Communications.EditOwn") : "Communications.Create");
    if (existing && !can_("Communications.EditAll") && existing.createdBy !== user.email) throw new Error("Communications.EditOwn is required for this campaign.");
    const now = new Date().toISOString(), sender = senderIdentity_(input.senderIdentityId, user);
    if (!String(input.name || "").trim()) throw new Error("Campaign name is required.");
    if (!sender) throw new Error("Select an authorised sender identity.");
    const status = existing && CAMPAIGN_STATUSES.includes(existing.status) ? existing.status : "DRAFT";
    const record = { id: existing && existing.id || PlatformStoreService.createId("CMP"), entityType: "CommunicationCampaign", name: String(input.name).trim().slice(0, 180), category: String(input.category || "General").slice(0, 80), channel: "EMAIL", status, senderIdentityId: sender.id, audienceDefinition: cleanAudienceDefinition_(input.audienceDefinition), templateId: String(input.templateId || BUILT_IN_TEMPLATE.id), subjectOverride: String(input.subjectOverride || "").slice(0, 500), bodyOverride: CommunicationMergeService.sanitizeHtml(String(input.bodyOverride || "")), plainTextOverride: String(input.plainTextOverride || "").slice(0, 15000), attachmentMetadata: Array.isArray(input.attachmentMetadata) ? input.attachmentMetadata.slice(0, 10).map(item => ({ name: String(item.name || "").slice(0, 180), driveFileId: String(item.driveFileId || "").slice(0, 180), status: "METADATA_ONLY" })) : [], createdBy: existing && existing.createdBy || user.email, createdAt: existing && existing.createdAt || now, updatedBy: user.email, updatedAt: now, scheduledAt: existing && existing.scheduledAt || "", approvedBy: existing && existing.approvedBy || "", approvedAt: existing && existing.approvedAt || "", provider: "MOCK", metadata: Object.assign({}, existing && existing.metadata || {}, { milestone: 1, externalSending: false }), version: Number(existing && existing.version || 0) + 1 };
    CommunicationRepositoryService.save("campaigns", record);
    recordEvent_(record.id, existing ? "UPDATED" : "CREATED", user, { version: record.version });
    AuditService.record(existing ? "CommunicationCampaignUpdated" : "CommunicationCampaignCreated", { type: "CommunicationCampaign", id: record.id }, { version: record.version, status: record.status, senderIdentityId: record.senderIdentityId, templateId: record.templateId, hasAudience: !!record.audienceDefinition.recipientTypes.length, contentHash: contentHash_(record) });
    return record;
  }
  function saveTemplate_(input) {
    const user = require_("Communications.Template.Manage"), existing = input.id && input.id !== BUILT_IN_TEMPLATE.id ? CommunicationRepositoryService.get("templates", input.id) : null, now = new Date().toISOString();
    if (!String(input.name || "").trim() || !String(input.subject || "").trim()) throw new Error("Template name and subject are required.");
    const htmlBody = CommunicationMergeService.sanitizeHtml(input.htmlBody || ""), fields = Array.from(new Set(CommunicationMergeService.extractFields([input.subject, htmlBody, input.plainTextBody].join(" "))));
    const record = { id: existing && existing.id || PlatformStoreService.createId("TPL"), entityType: "CommunicationTemplate", name: String(input.name).trim().slice(0, 180), category: String(input.category || "General").slice(0, 80), subject: String(input.subject).slice(0, 500), htmlBody, plainTextBody: String(input.plainTextBody || CommunicationMergeService.plainTextFromHtml(htmlBody)).slice(0, 15000), supportedMergeFields: fields, status: TEMPLATE_STATUSES.includes(input.status) ? input.status : existing && existing.status || "ACTIVE", version: Number(existing && existing.version || 0) + 1, createdBy: existing && existing.createdBy || user.email, createdAt: existing && existing.createdAt || now, updatedBy: user.email, updatedAt: now };
    CommunicationRepositoryService.save("templates", record); AuditService.record("CommunicationTemplateSaved", { type: "CommunicationTemplate", id: record.id }, { version: record.version, status: record.status, mergeFieldCount: fields.length, contentHash: contentHash_(record) }); return record;
  }
  function saveAudience_(input) {
    const user = require_("Communications.Audience.Build"), existing = input.id ? CommunicationRepositoryService.get("audiences", input.id) : null, now = new Date().toISOString();
    if (!String(input.name || "").trim()) throw new Error("Audience name is required.");
    const definition = cleanAudienceDefinition_(input), resolved = CommunicationAudienceService.resolve(definition, { summaryOnly: true });
    const record = { id: existing && existing.id || PlatformStoreService.createId("AUDI"), entityType: "SavedAudience", name: String(input.name).trim().slice(0, 180), description: String(input.description || "").slice(0, 1000), filters: definition.filters, recipientTypes: definition.recipientTypes, lastResolution: summaryResolution_(resolved), createdBy: existing && existing.createdBy || user.email, createdAt: existing && existing.createdAt || now, updatedBy: user.email, updatedAt: now };
    CommunicationRepositoryService.save("audiences", record); AuditService.record("CommunicationAudienceSaved", { type: "SavedAudience", id: record.id }, { recipientTypes: record.recipientTypes, filterKeys: Object.keys(record.filters), uniqueEmailCount: resolved.uniqueEmailCount }); return record;
  }
  function resolveAudience_(input) { require_("Communications.Audience.Build"); const result = CommunicationAudienceService.resolve(cleanAudienceDefinition_(input.audienceDefinition || input)); AuditService.record("CommunicationAudienceResolved", { type: "CommunicationCampaign", id: String(input.campaignId || "preview") }, { counts: summaryResolution_(result), recipientTypes: result.definition.recipientTypes, filterKeys: Object.keys(result.definition.filters) }); return result; }
  function preview_(input) {
    const user = require_("Communications.View"), campaign = campaignInput_(input), sender = senderIdentity_(campaign.senderIdentityId, user); if (!sender) throw new Error("The sender identity is unavailable.");
    const audience = CommunicationAudienceService.resolve(cleanAudienceDefinition_(campaign.audienceDefinition)), recipient = audience.recipients.find(item => item.id === input.recipientId) || audience.recipients[Number(input.recipientIndex || 0)] || sampleRecipient_();
    const content = content_(campaign), mergeData = Object.assign({}, recipient.mergeData || {}, { Sender: { DisplayName: sender.displayName } }), subject = CommunicationMergeService.render(content.subject, mergeData, { plainText: true }), html = CommunicationMergeService.render(content.htmlBody, mergeData), plain = CommunicationMergeService.render(content.plainTextBody, mergeData, { plainText: true }), unresolved = Array.from(new Set(subject.unresolved.concat(html.unresolved, plain.unresolved)));
    if (campaign.id) recordEvent_(campaign.id, "PREVIEWED", user, { recipientEntityType: recipient.entityType, unresolvedCount: unresolved.length });
    return { campaignId: campaign.id || "", recipient: summaryRecipient_(recipient), subject: subject.output, htmlBody: html.output, plainTextBody: plain.output, unresolved, audience: summaryResolution_(audience), mergeFields: Array.from(new Set(subject.fields.concat(html.fields, plain.fields))) };
  }
  function sendTest_(input) {
    const user = require_("Communications.SendTest"), campaign = campaignInput_(input); if (!campaign.id) throw new Error("Save the campaign draft before sending a test.");
    const testEmail = CommunicationAudienceService.normaliseEmail(input.testEmail || user.email); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(testEmail)) throw new Error("A valid test recipient email is required.");
    const sender = senderIdentity_(campaign.senderIdentityId, user); if (!sender) throw new Error("The sender identity is unavailable.");
    const audience = CommunicationAudienceService.resolve(cleanAudienceDefinition_(campaign.audienceDefinition)); if (!audience.uniqueEmailCount) throw new Error("Resolve at least one valid audience recipient before testing.");
    const preview = preview_({ campaign: campaign, recipientIndex: input.recipientIndex || 0 }), provider = CommunicationEmailProviderService.get("MOCK"), response = provider.sendTestMessage({ to: testEmail, sender: sender, subject: preview.subject, htmlBody: preview.htmlBody, plainTextBody: preview.plainTextBody, simulateFailure: !!input.simulateFailure });
    const now = new Date().toISOString(), updated = CommunicationRepositoryService.update("campaigns", campaign.id, { status: "TESTED", provider: "MOCK", updatedBy: user.email, updatedAt: now, metadata: Object.assign({}, campaign.metadata || {}, { lastTestAt: now, externalSending: false, recipientSnapshot: summaryResolution_(audience), recipientSnapshotHash: snapshotHash_(audience.recipients) }) });
    const recipient = { id: PlatformStoreService.createId("CREC"), entityType: "CommunicationRecipient", campaignId: campaign.id, recipientType: "OTHER", relatedEntityType: preview.recipient.entityType, relatedEntityId: preview.recipient.entityId, emailAddress: testEmail, displayName: preview.recipient.displayName || user.displayName, status: "TESTED", suppressionReason: "", providerMessageId: response.providerMessageId, provider: "MOCK", mock: true, createdAt: now, updatedAt: now };
    CommunicationRepositoryService.save("recipients", recipient); recordEvent_(campaign.id, "TEST_SENT", user, { recipientId: recipient.id, provider: "MOCK", mock: true, externalDelivery: false, unresolvedCount: preview.unresolved.length }); AuditService.record("CommunicationTestSent", { type: "CommunicationCampaign", id: campaign.id }, { provider: "MOCK", mock: true, externalDelivery: false, recipientCount: 1, audienceSnapshot: summaryResolution_(audience), contentHash: contentHash_(campaign) });
    return { campaign: updated, recipient: summaryRecipient_(recipient), provider: { id: "MOCK", status: response.status, externalDelivery: false }, preview };
  }
  function archiveCampaign_(input) { const campaign = CommunicationRepositoryService.get("campaigns", input.id); if (!campaign) throw new Error("Campaign not found."); const user = require_(can_("Communications.EditAll") ? "Communications.EditAll" : "Communications.EditOwn"); if (!can_("Communications.EditAll") && campaign.createdBy !== user.email) throw new Error("Communications.EditOwn is required for this campaign."); const updated = CommunicationRepositoryService.update("campaigns", campaign.id, { status: "ARCHIVED", updatedBy: user.email, updatedAt: new Date().toISOString(), version: Number(campaign.version || 0) + 1 }); recordEvent_(campaign.id, "CANCELLED", user, { archived: true }); AuditService.record("CommunicationCampaignArchived", { type: "CommunicationCampaign", id: campaign.id }, { version: updated.version }); return updated; }
  function senderIdentities_(user) {
    const values = [];
    if (can_("Communications.SendTest")) values.push({ id: "SYSTEM-TEST", displayName: "SpecCentral Test Mailer", emailAddress: "no-send@spec-central.invalid", type: "SYSTEM_TEST", provider: "MOCK", enabled: true, available: true, requiresSendAsPermission: false, replyToAddress: user.email, status: "Mock provider active — no external delivery" });
    if (can_("Communications.Create")) values.push({ id: "USER-MAILBOX", displayName: user.displayName || user.email, emailAddress: user.email, type: "USER_MAILBOX", provider: "MICROSOFT_GRAPH", enabled: true, available: false, requiresSendAsPermission: true, replyToAddress: user.email, status: "Preview only — Graph not configured" });
    if (can_("Communications.Send")) values.push({ id: "SHARED-SCHOOLS-SPECTACULAR", displayName: "Schools Spectacular", emailAddress: "schoolsspectacular@det.nsw.edu.au", type: "SHARED_MAILBOX", provider: "MICROSOFT_GRAPH", enabled: false, available: false, requiresSendAsPermission: true, replyToAddress: "schoolsspectacular@det.nsw.edu.au", status: "Shared mailbox unavailable — approval and Send As permission required" });
    return values;
  }
  function senderIdentity_(id, user) { return senderIdentities_(user).find(item => item.id === String(id || "")) || null; }
  function campaignInput_(input) { if (input.campaign && typeof input.campaign === "object") return input.campaign; const campaign = CommunicationRepositoryService.get("campaigns", input.campaignId || input.id); if (!campaign) throw new Error("Campaign not found."); return campaign; }
  function content_(campaign) { const template = templates_().find(item => item.id === campaign.templateId) || BUILT_IN_TEMPLATE; return { subject: campaign.subjectOverride || template.subject || "", htmlBody: campaign.bodyOverride || template.htmlBody || "", plainTextBody: campaign.plainTextOverride || template.plainTextBody || CommunicationMergeService.plainTextFromHtml(campaign.bodyOverride || template.htmlBody || "") }; }
  function templates_() { return [BUILT_IN_TEMPLATE].concat(CommunicationRepositoryService.list("templates")); }
  function cleanAudienceDefinition_(input) { const value = input || {}, allowed = CommunicationAudienceService.getSupportedFilters(), filters = {}; Object.keys(value.filters || {}).forEach(key => { if (allowed.includes(key) && String(value.filters[key] || "").trim()) filters[key] = String(value.filters[key]).trim().slice(0, 250); }); return { recipientTypes: Array.from(new Set((value.recipientTypes || []).filter(type => CommunicationAudienceService.recipientTypes().includes(type)))), filters, savedAudienceId: String(value.savedAudienceId || "") }; }
  function recordEvent_(campaignId, type, user, metadata) { return CommunicationRepositoryService.save("events", { id: PlatformStoreService.createId("CEVT"), entityType: "CommunicationEvent", campaignId: String(campaignId || ""), recipientId: String(metadata && metadata.recipientId || ""), type: String(type || "UPDATED"), timestamp: new Date().toISOString(), actor: user && user.email || "system", provider: String(metadata && metadata.provider || "MOCK"), metadata: PlatformStoreService.safeData(metadata || {}) }); }
  function metrics_(campaigns, templates, audiences, events) { return { draftCampaigns: campaigns.filter(item => item.status === "DRAFT").length, testedCampaigns: campaigns.filter(item => item.status === "TESTED").length, scheduledCampaigns: campaigns.filter(item => item.status === "SCHEDULED").length, activeTemplates: templates.filter(item => item.status !== "ARCHIVED").length, savedAudiences: audiences.length, testEvents: events.filter(item => item.type === "TEST_SENT").length, realMessagesSent: 0 }; }
  function communicationCapabilities_(user) { return Object.keys(AuthorizationService.getModel().capabilities.reduce((map, item) => { if (item.indexOf("Communications.") === 0) map[item] = AuthorizationService.hasCapability(user, item); return map; }, {})).reduce((map, key) => { map[key] = AuthorizationService.hasCapability(user, key); return map; }, {}); }
  function summaryResolution_(value) { return { estimatedRecipientCount: Number(value.estimatedRecipientCount || 0), uniqueEmailCount: Number(value.uniqueEmailCount || 0), duplicatesRemoved: Number(value.duplicatesRemoved || 0), invalidEmailCount: Number(value.invalidEmailCount || 0), missingEmailCount: Number(value.missingEmailCount || 0), excludedCount: Number(value.excludedCount || 0), resolvedAt: value.resolvedAt || new Date().toISOString() }; }
  function summaryRecipient_(recipient) { return { id: recipient.id || "", entityType: recipient.entityType || recipient.recipientType || "OTHER", entityId: recipient.entityId || recipient.relatedEntityId || "", emailAddress: recipient.emailAddress || "", displayName: recipient.displayName || "", matchReasons: recipient.matchReasons || [], status: recipient.status || "" }; }
  function sampleRecipient_() { return { id: "SAMPLE", entityType: "PARTICIPANT", entityId: "SAMPLE", emailAddress: "sample@spec-central.invalid", displayName: "Sample Recipient", mergeData: { Participant: { FirstName: "Sample", FullName: "Sample Recipient" }, School: { Name: "Sample School" }, Teacher: { FirstName: "Taylor", FullName: "Taylor Teacher" }, Item: { Name: "Sample Item" }, Category: { Name: "Sample Category" }, Segment: { Name: "Sample Segment" }, Group: { Name: "Sample Group" }, Staff: { FirstName: "Morgan", FullName: "Morgan Staff" }, Sender: {} }, matchReasons: ["Safe sample recipient"] }; }
  function snapshotHash_(recipients) { return hash_((recipients || []).map(item => [CommunicationAudienceService.normaliseEmail(item.emailAddress), item.entityType, item.entityId].join("|")).sort().join("\n")); }
  function contentHash_(record) { return hash_([record.subjectOverride || record.subject, record.bodyOverride || record.htmlBody, record.plainTextOverride || record.plainTextBody, record.templateId].join("|")); }
  function hash_(value) { const bytes = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, String(value || "")); return Utilities.base64EncodeWebSafe(bytes).replace(/=+$/, "").slice(0, 32); }
  function require_(capability) { return UserContextService.requireCapability(capability); }
  function can_(capability) { return UserContextService.hasCapability(capability); }
  function success_(command, data) { return { ok: true, command, data, generatedAt: new Date().toISOString() }; }
  function failure_(command, code, message) { return { ok: false, command, errorCode: code, error: String(message || "Communication command failed."), generatedAt: new Date().toISOString() }; }
  return { getWorkspace, execute, getSenderIdentities: () => senderIdentities_(require_("Communications.View")), getProviderStatus: CommunicationEmailProviderService.status, getCommands: () => Object.assign({}, COMMANDS), statuses: () => CAMPAIGN_STATUSES.slice() };
})();
