/** Read-only cache refresh coordinator. No source spreadsheet writes occur here. */
const DataSyncService = (() => {
  const MODULES = ["participants", "staff", "timeline", "show-run", "attendance", "search", "dashboard", "administration"];
  const INVALIDATION_MAP = {
    participantUpdated: ["participants", "category summaries", "dashboard", "search", "relationships"],
    timelineEventUpdated: ["timeline", "calendar", "rehearsals", "event manager", "participant schedules", "dashboard", "search"],
    attendanceMarked: ["attendance event", "attendance summary", "participant attendance history", "dashboard attention"]
  };
  function sync(request) { const user = UserContextService.getCurrent(); if (!AuthorizationService.hasCapability(user, "Data.Sync")) throw new Error("Data.Sync is required."); const allowed = allowedModules_(user), requested = unique_((request && request.modules && request.modules.length) ? request.modules : allowed), started = Date.now(); const results = requested.filter(item => allowed.includes(item)).map(item => refresh_(item, user)); return { startedAt: new Date(started).toISOString(), completedAt: new Date().toISOString(), durationMs: Date.now() - started, results }; }
  function refreshPage(module) { const user = UserContextService.getCurrent(); const required = { participants: "Participants.View", timeline: "Calendar.View", "show-run": "Operations.View", attendance: "Attendance.View", staff: "Operations.View", administration: "Administration.View", dashboard: "Calendar.View", search: "Participants.View" }[module]; if (required && !AuthorizationService.hasCapability(user, required)) throw new Error(`${required} is required.`); return refresh_(MODULES.includes(module) ? module : "dashboard", user); }
  function refresh_(module, user) { const started = Date.now(); try { invalidate(module, user); const value = load_(module, user); return { source: title_(module), status: "Connected", records: count_(value), durationMs: Date.now() - started, warnings: [] }; } catch (err) { return { source: title_(module), status: "Failed", records: 0, durationMs: Date.now() - started, warnings: [err && err.message ? err.message : String(err)] }; } }
  function invalidate(module, user) { const map = { participants: ["participants:portal", "participants:all", "participants:groups", "participants:schools", "dashboard", "search", "relationships", "administration"], staff: ["staff:all", "staff:directory", "dashboard", "administration"], timeline: ["timeline", "calendar", "rehearsals", "event-manager", "dashboard", "search", "relationships", "administration"], "show-run": ["show-run:data:v1", "search", "relationships", "administration"], attendance: ["attendance", "dashboard", "administration"], search: ["search"], dashboard: ["dashboard"], administration: ["administration"] }; (map[module] || [module]).forEach(PerformanceCacheService.remove); if (["participants", "timeline", "show-run", "staff", "search"].includes(module)) CacheService.getScriptCache().put("SC_SEARCH_EPOCH", String(Date.now()), 21600); if (user) { ["dashboard", "calendar", "administration", "staff-directory", "production-overview"].forEach(prefix => PerformanceCacheService.removeUser(PerformanceCacheService.userProjectionKey(prefix, user))); } if (module === "timeline") CacheService.getScriptCache().remove("SPEC_TIMELINE_EVENTS_V3"); if (module === "attendance" && AttendanceService.invalidate) AttendanceService.invalidate(); if (module === "staff" && StaffService.refresh) StaffService.refresh(); }
  function load_(module, user) { if (module === "participants") return ParticipantService.getPortalData(); if (module === "staff") return StaffService.getAll(); if (module === "timeline") return TimelineService.getCalendarData(); if (module === "show-run") return ShowRunService.refresh(); if (module === "attendance") return { summary: AttendanceService.getSummary(), events: AttendanceService.getEvents() }; if (module === "search") return { status: "Index rebuilt lazily" }; if (module === "dashboard") return DashboardService.getContext(); if (module === "administration") return AuthorizationService.hasCapability(user, "Administration.View") ? AdministrationService.getData() : { status: "Not permitted" }; return {}; }
  function count_(value) { if (Array.isArray(value)) return value.length; if (!value || typeof value !== "object") return 0; if (Array.isArray(value.participants)) return value.participants.length; if (Array.isArray(value.items)) return value.items.length; if (Array.isArray(value.events)) return value.events.length; if (value.events && Array.isArray(value.events.data)) return value.events.data.length; return Object.keys(value).length; }
  function unique_(values) { return Array.from(new Set((values || []).map(value => String(value || "").toLowerCase()).filter(Boolean))); }
  function allowedModules_(user) { const modules = ["dashboard"]; if (AuthorizationService.hasCapability(user, "Participants.View")) modules.push("participants", "search"); if (AuthorizationService.hasCapability(user, "Calendar.View")) modules.push("timeline"); if (AuthorizationService.hasCapability(user, "Attendance.View")) modules.push("attendance"); if (AuthorizationService.hasCapability(user, "Operations.View")) modules.push("staff", "show-run"); if (AuthorizationService.hasCapability(user, "Administration.View")) modules.push("administration"); return unique_(modules); }
  function title_(value) { return String(value || "").replace(/(^|[-_])([a-z])/g, (_, prefix, letter) => `${prefix ? " " : ""}${letter.toUpperCase()}`); }
  function getArchitecture() { return { modules: MODULES.slice(), invalidationMap: JSON.parse(JSON.stringify(INVALIDATION_MAP)), readOnly: true, businessWritesEnabled: false }; }
  return { sync, refreshPage, invalidate, getArchitecture };
})();
