/** Queue and adapter registry for manually invoked background jobs. */
const JobService = (() => {
  const TYPES = ["CacheRefresh", "RelationshipRebuild", "SearchIndexRebuild", "AttendanceSync", "TimelineSync", "ParticipantSync", "PermissionRefresh"];
  const handlers = {};
  function register(jobType, handler) { if (!TYPES.includes(jobType) || typeof handler !== "function") throw new Error("Invalid job registration."); handlers[jobType] = handler; }
  function enqueue(jobType, payload, options) { if (!TYPES.includes(jobType)) throw new Error(`Unknown job type ${jobType}.`); const value = options || {}; return PlatformStoreService.put("jobs", { id: PlatformStoreService.createId("JOB"), entityType: "Job", jobType, status: "Pending", payload: PlatformStoreService.safeData(payload || {}), priority: value.priority || "Medium", requestedBy: Session.getActiveUser().getEmail() || "system", createdAt: new Date().toISOString(), startedAt: "", completedAt: "", attempts: 0, error: "" }, 80); }
  function runNext() { const job = list({ status: "Pending" })[0]; if (!job) return null; if (!handlers[job.jobType]) return PlatformStoreService.update("jobs", job.id, { status: "Waiting for Adapter" }, 80); PlatformStoreService.update("jobs", job.id, { status: "Running", startedAt: new Date().toISOString(), attempts: (job.attempts || 0) + 1 }, 80); try { const result = handlers[job.jobType](job.payload); AuditService.record("JobCompleted", { type: "Job", id: job.id }, { jobType: job.jobType }); return PlatformStoreService.update("jobs", job.id, { status: "Completed", completedAt: new Date().toISOString(), result: PlatformStoreService.safeData(result) }, 80); } catch (err) { return PlatformStoreService.update("jobs", job.id, { status: "Failed", completedAt: new Date().toISOString(), error: err && err.message ? err.message : String(err) }, 80); } }
  function list(filters) { const status = filters && filters.status; return PlatformStoreService.list("jobs").filter(item => !status || item.status === status); }
  function getRegistry() { return TYPES.map(jobType => ({ jobType, adapterConnected: !!handlers[jobType] })); }
  return { register, enqueue, runNext, list, getRegistry, TYPES };
})();
