/** Shared compressed server cache. Canonical data uses script cache; permission projections use user cache. */
const PerformanceCacheService = (() => {
  const PREFIX = "SC_PERF_V1", CHUNK_SIZE = 80000, MAX_CHUNKS = 12;
  function getOrLoad(key, ttl, loader) { const value = get_(CacheService.getScriptCache(), key); if (value !== null) return value; const loaded = loader(); put_(CacheService.getScriptCache(), key, loaded, ttl); return loaded; }
  function getOrLoadUser(key, ttl, loader) { const value = get_(CacheService.getUserCache(), key); if (value !== null) return value; const loaded = loader(); put_(CacheService.getUserCache(), key, loaded, ttl); return loaded; }
  function get_(cache, key) { const base = cacheKey_(key), raw = cache.get(base); if (!raw) return null; try { const manifest = JSON.parse(raw); if (!manifest.chunks || manifest.chunks > MAX_CHUNKS) return null; const keys = Array.from({ length: manifest.chunks }, (_, i) => `${base}:${i}`), values = cache.getAll(keys), encoded = keys.map(item => values[item] || "").join(""); if (!encoded) return null; return JSON.parse(Utilities.ungzip(Utilities.newBlob(Utilities.base64Decode(encoded))).getDataAsString("UTF-8")); } catch (err) { remove_(cache, key); return null; } }
  function put_(cache, key, value, ttl) { try { const json = JSON.stringify(value), encoded = Utilities.base64Encode(Utilities.gzip(Utilities.newBlob(json, "application/json")).getBytes()), chunks = []; for (let i = 0; i < encoded.length; i += CHUNK_SIZE) chunks.push(encoded.slice(i, i + CHUNK_SIZE)); if (!chunks.length || chunks.length > MAX_CHUNKS) return false; const base = cacheKey_(key), entries = {}; chunks.forEach((chunk, i) => entries[`${base}:${i}`] = chunk); cache.putAll(entries, Math.max(30, Number(ttl) || 60)); cache.put(base, JSON.stringify({ chunks: chunks.length, bytes: json.length, cachedAt: new Date().toISOString() }), Math.max(30, Number(ttl) || 60)); return true; } catch (err) { Logger.log(`Performance cache skipped for ${key}: ${err && err.message ? err.message : err}`); return false; } }
  function remove(key) { remove_(CacheService.getScriptCache(), key); }
  function removeUser(key) { remove_(CacheService.getUserCache(), key); }
  function remove_(cache, key) { const base = cacheKey_(key); let chunks = MAX_CHUNKS; try { chunks = Math.min(MAX_CHUNKS, Number(JSON.parse(cache.get(base) || "{}").chunks) || MAX_CHUNKS); } catch (err) {} cache.removeAll([base].concat(Array.from({ length: chunks }, (_, i) => `${base}:${i}`))); }
  function cacheKey_(key) { const digest = Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, String(key || ""))).replace(/=+$/, "").slice(0, 32); return `${PREFIX}:${digest}`; }
  function userProjectionKey(prefix, user) { const record = user || {}; return [prefix, record.email, record.role, JSON.stringify(record.scope || {}), (record.capabilities || []).slice().sort().join(",")].join("|"); }
  return { getOrLoad, getOrLoadUser, remove, removeUser, userProjectionKey };
})();
